  export const CountryCodes = [
    { code: "+1", flag: "🇺🇸", country: "USA" },
    { code: "+1", flag: "🇨🇦", country: "Canada" },
    { code: "+44", flag: "🇬🇧", country: "UK" },
    { code: "+91", flag: "🇮🇳", country: "India" },
    { code: "+61", flag: "🇦🇺", country: "Australia" },
    { code: "+49", flag: "🇩🇪", country: "Germany" },
    { code: "+33", flag: "🇫🇷", country: "France" },
    { code: "+39", flag: "🇮🇹", country: "Italy" },
    { code: "+34", flag: "🇪🇸", country: "Spain" },
    { code: "+81", flag: "🇯🇵", country: "Japan" },
    { code: "+55", flag: "🇧🇷", country: "Brazil" },
    { code: "+7", flag: "🇷🇺", country: "Russia" },
    { code: "+52", flag: "🇲🇽", country: "Mexico" },
    { code: "+20", flag: "🇪🇬", country: "Egypt" },
    { code: "+27", flag: "🇿🇦", country: "South Africa" },
    { code: "+63", flag: "🇵🇭", country: "Philippines" },
    { code: "+82", flag: "🇰🇷", country: "South Korea" },
    { code: "+31", flag: "🇳🇱", country: "Netherlands" },
    { code: "+66", flag: "🇹🇭", country: "Thailand" },
    { code: "+48", flag: "🇵🇱", country: "Poland" },
    { code: "+46", flag: "🇸🇪", country: "Sweden" },
    { code: "+32", flag: "🇧🇪", country: "Belgium" },
    { code: "+64", flag: "🇳🇿", country: "New Zealand" },
    { code: "+86", flag: "🇨🇳", country: "China" },
    { code: "+971", flag: "🇦🇪", country: "United Arab Emirates" },
    { code: "+65", flag: "🇸🇬", country: "Singapore" },
    { code: "+972", flag: "🇮🇱", country: "Israel" },
    { code: "+90", flag: "🇹🇷", country: "Turkey" },
    { code: "+34", flag: "🇦🇷", country: "Argentina" },
    { code: "+46", flag: "🇩🇰", country: "Denmark" },
    { code: "+43", flag: "🇦🇹", country: "Austria" },
    { code: "+92", flag: "🇵🇰", country: "Pakistan" },
    { code: "+98", flag: "🇮🇷", country: "Iran" },
    { code: "+351", flag: "🇵🇹", country: "Portugal" },
    { code: "+380", flag: "🇺🇦", country: "Ukraine" },
    { code: "+30", flag: "🇬🇷", country: "Greece" },
    { code: "+886", flag: "🇹🇼", country: "Taiwan" },
    { code: "+62", flag: "🇮🇩", country: "Indonesia" },
    { code: "+256", flag: "🇺🇬", country: "Uganda" },
    { code: "+593", flag: "🇪🇨", country: "Ecuador" },
    { code: "+225", flag: "🇨🇮", country: "Ivory Coast" },
    { code: "+212", flag: "🇲🇦", country: "Morocco" },
    { code: "+974", flag: "🇶🇦", country: "Qatar" },
    { code: "+507", flag: "🇵🇦", country: "Panama" },
    { code: "+383", flag: "🇽🇰", country: "Kosovo" },
    { code: "+964", flag: "🇮🇶", country: "Iraq" },
    { code: "+962", flag: "🇯🇴", country: "Jordan" },
    { code: "+218", flag: "🇱🇾", country: "Libya" },
    { code: "+880", flag: "🇧🇩", country: "Bangladesh" }
];
